# Generated by Django 6.0.6 on 2026-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzmodel',
            name='transscript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
