# Generated by Django 6.0.6 on 2026-06-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0002_quizzmodel_transscript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzmodel',
            old_name='transscript',
            new_name='transcript',
        ),
    ]
