# Generated by Django 6.0.6 on 2026-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0003_rename_transscript_quizzmodel_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='question_options',
            field=models.JSONField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='question_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
