# Generated by Django 6.0.6 on 2026-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0004_questionsmodel_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='question_options',
            field=models.JSONField(default=list, max_length=500),
        ),
    ]
